// <auto-generated />
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(MVCContext))]
    [Migration("20220110212433_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC.Models.Category", b =>
                {
                    b.Property<int>("c_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("c_ID"), 1L, 1);

                    b.Property<string>("c_emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("MVC.Models.Product", b =>
                {
                    b.Property<int>("p_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("p_Id"), 1L, 1);

                    b.Property<int>("c_ID")
                        .HasColumnType("int");

                    b.Property<string>("p_emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("p_Id");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
